name: Deploy GitHub Pages
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build package with Vite
        run: |
          npm i
          npm run build
      - name: Commit to gh-pages branch
        run: |
          git config --global user.email "sean@seanhay.com"
          git config --global user.name "Sean Hay"
          git checkout --orphan gh-pages
          git reset
          git add -f docs
          git commit -m "Pushing build files"
          git push -f origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
